import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import Fastify from 'fastify';
import jwt from '@fastify/jwt';
import { prisma } from '../src/shared/database/prisma-client.js';
import { debtRoutes } from '../src/modules/sale-app/debt-routes.js';
import { receiptAssistantRoutes, validateBillFields } from '../src/modules/receipt-assistant/routes.js';
if (!['localhost', '127.0.0.1'].includes(new URL(process.env.DATABASE_URL!).hostname))
    throw Error('LOCAL ONLY');
const app = Fastify();
await app.register(jwt, { secret: randomUUID() });
await app.register(receiptAssistantRoutes);
await app.register(debtRoutes);
const org = await prisma.organization.create({ data: { name: 'Receipt QA ' + randomUUID() } });
const other = await prisma.organization.create({ data: { name: 'Receipt QA isolation ' + randomUUID() } });
try {
    const user = await prisma.user.create({ data: { orgId: org.id, email: randomUUID() + '@qa.invalid', fullName: 'QA', passwordHash: 'none', role: 'admin' } });
    const member = await prisma.user.create({ data: { orgId: org.id, email: randomUUID() + '@qa.invalid', fullName: 'Member', passwordHash: 'none', role: 'member' } });
    const c = await prisma.contact.create({ data: { orgId: org.id, fullName: 'Khách QA' } });
    const alien = await prisma.contact.create({ data: { orgId: other.id, fullName: 'Other' } });
    const o = await prisma.order.create({ data: { orgId: org.id, contactId: c.id, createdByUserId: user.id, orderCode: 'QA-' + randomUUID(), totalAmount: 1000, totalAmountValue: 1000, debtAmountValue: 1000, paidAmount: 0, status: 'completed' } });
    const headers = { authorization: 'Bearer ' + app.jwt.sign({ id: user.id, orgId: org.id, role: 'admin', email: user.email }) };
    const call = async (path: string, body?: any, h = headers) => { const r = await app.inject({ method: body ? 'POST' : 'GET', url: '/api/v1/receipt-assistant' + path, headers: h, ...(body ? { payload: body } : {}) }); return { status: r.statusCode, data: r.json() }; };
    async function make(amount = 400, txref = randomUUID(), imageHash = randomUUID()) {
        const bill = { id: randomUUID(), hash: imageHash, url: 'https://example.invalid/' + randomUUID() + '.png', fields: { amount, paymentDate: '2026-09-25', transactionRef: txref } };
        const d = await prisma.receiptAssistantDraft.create({ data: { orgId: org.id, createdById: user.id, bills: [bill], expiresAt: new Date(Date.now() + 3600000) } });
        return { draftId: d.id, contactId: c.id, action: 'collect', bills: [{ id: bill.id, ...bill.fields }] };
    }
    const memberToken = { authorization: 'Bearer ' + app.jwt.sign({ id: member.id, orgId: org.id, role: 'admin', email: member.email }) };
    assert.equal((await call('/customers', undefined, memberToken)).status, 403, 'fresh role overrides JWT');
    assert.equal((await call('/customers/' + alien.id)).status, 404, 'org scope');
    const input = await make();
    const preview = await call('/preview', input);
    assert.equal(preview.status, 200, JSON.stringify(preview));
    assert.equal(preview.data.debtAfter, 600);
    const confirmed = await call('/confirm', { draftId: input.draftId, previewToken: preview.data.previewToken });
    assert.equal(confirmed.status, 200, JSON.stringify(confirmed));
    assert.equal(confirmed.data.remainingDebt, 600);
    assert.deepEqual((await call('/confirm', { draftId: input.draftId, previewToken: preview.data.previewToken })).data, confirmed.data, 'idempotent');
    assert.equal(await prisma.customerPayment.count({ where: { orgId: org.id } }), 1);
    const duplicate = await make(400, input.bills[0].transactionRef);
    const dp = await call('/preview', duplicate);
    assert.equal(dp.data.canConfirm, false);
    assert.equal((await call('/confirm', { draftId: duplicate.draftId, previewToken: dp.data.previewToken })).status, 409);
    const source = await prisma.receiptAssistantDraft.findUniqueOrThrow({where:{id:input.draftId}});
    const sameImage = await make(123,randomUUID(),(source.bills as any[])[0].hash);
    assert.equal((await call('/preview',sameImage)).data.canConfirm,false,'image hash detects changed amount/ref');
    const expired = await make();
    await prisma.receiptAssistantDraft.update({where:{id:expired.draftId},data:{expiresAt:new Date(0)}});
    assert.equal((await call('/preview',expired)).status,410);
    const malformed=await make();
    assert.equal((await call('/preview',{...malformed,bills:[null]})).status,400);
    const restored=(await call('/drafts/'+input.draftId)).data;
    assert.equal(restored.status,'confirmed');assert.equal(restored.contactId,c.id);assert.equal(restored.bills[0].fields.amount,400);
    const oversizedAttach=await call('/preview',{...await make(500),action:'attach',paymentId:confirmed.data.paymentId});
    assert(oversizedAttach.data.warnings.some((w:string)=>w.includes('lớn hơn số tiền phiếu')));
    assert.equal(oversizedAttach.data.canConfirm,true);
    const a = await make(100);
    a.action = 'attach';
    const ap = await call('/preview', { ...a, paymentId: confirmed.data.paymentId });
    const ac = await call('/confirm', { draftId: a.draftId, previewToken: ap.data.previewToken });
    assert.equal(ac.data.amount, 400);
    assert.equal(ac.data.remainingDebt, 600);
    assert.equal(ac.data.proofUrls.length, 2);
    const advance = await make(900);
    advance.action = 'advance';
    const avp = await call('/preview', advance);
    const avc = await call('/confirm', { draftId: advance.draftId, previewToken: avp.data.previewToken });
    assert.equal(avc.data.advanceCredit, 900);
    assert.equal(avc.data.remainingDebt, 600);
    const history=(await app.inject({url:'/api/v1/sale-app/debt/customers/'+c.id+'/payments',headers})).json();
    assert.equal(history.payments.find((p:any)=>p.id===avc.data.paymentId).unallocated_amount,900);
    const ledger=(await app.inject({url:'/api/v1/sale-app/debt/customers/'+c.id+'/ledger',headers})).json();
    const advanceRow=ledger.rows.find((r:any)=>r.unallocated_amount===900);
    assert.equal(advanceRow.description,'Khách ứng trước (chưa phân bổ)');
    assert.equal(advanceRow.credit,900);assert.equal(ledger.totals.closing,-300);
    const companyLedger=(await app.inject({url:'/api/v1/sale-app/debt/ledger',headers})).json();
    assert.equal(companyLedger.rows.find((r:any)=>r.unallocated_amount===900).description,'Khách ứng trước (chưa phân bổ)');
    assert.equal(companyLedger.company_closing,-300);

    const stale = await make(100);
    const sp = await call('/preview', stale);
    await prisma.order.update({ where: { id: o.id }, data: { debtAmountValue: 500, paidAmount: 500 } });
    assert.equal((await call('/confirm', { draftId: stale.draftId, previewToken: sp.data.previewToken })).status, 409);
    const over = await call('/preview', { ...await make(1000) });
    assert.equal(over.data.canConfirm, false);
    const concurrency = await make(100);
    const cp = await call('/preview', concurrency);
    const responses = await Promise.all([call('/confirm', { draftId: concurrency.draftId, previewToken: cp.data.previewToken }), call('/confirm', { draftId: concurrency.draftId, previewToken: cp.data.previewToken })]);
    assert(responses.some(x => x.status === 200));
    assert(responses.every(x => [200, 409].includes(x.status)), JSON.stringify(responses));
    assert.equal(await prisma.customerPayment.count({ where: { orgId: org.id } }), 3);
    const invalid = await make();
    invalid.bills[0].paymentDate = '2026-02-30';
    assert.equal((await call('/preview', invalid)).status, 400);
    assert.throws(() => validateBillFields([{ amount: 1.2, paymentDate: '2026-09-25' }], 'collect'));
    // Exercise the original manual endpoint concurrently with assistant confirmation.
    const crossContact=await prisma.contact.create({data:{orgId:org.id,fullName:'Cross-path QA'}});
    const crossOrder=await prisma.order.create({data:{orgId:org.id,contactId:crossContact.id,createdByUserId:user.id,orderCode:'QA-'+randomUUID(),totalAmount:1000,totalAmountValue:1000,debtAmountValue:1000,paidAmount:0,status:'completed'}});
    const crossInput={...await make(300),contactId:crossContact.id};
    const crossPreview=await call('/preview',crossInput);
    const [assistantResponse,manualResponse]=await Promise.all([
      call('/confirm',{draftId:crossInput.draftId,previewToken:crossPreview.data.previewToken}),
      app.inject({method:'POST',url:'/api/v1/sale-app/debt/payments',headers,payload:{contactId:crossContact.id,amount:200,paymentMethod:'cash',paymentDate:'2026-09-25'}})
    ]);
    assert([200,409].includes(assistantResponse.status),JSON.stringify(assistantResponse));
    assert([201,409].includes(manualResponse.statusCode),manualResponse.body);
    assert(assistantResponse.status===200||manualResponse.statusCode===201);
    const successfulAmount=(assistantResponse.status===200?300:0)+(manualResponse.statusCode===201?200:0);
    const crossBalance=await prisma.order.findUniqueOrThrow({where:{id:crossOrder.id}});
    assert.equal(Number(crossBalance.paidAmount),successfulAmount,'No cross-path lost paid amount');
    assert.equal(Number(crossBalance.debtAmountValue),1000-successfulAmount,'Debt matches committed receipts');
    const crossPayments=await prisma.customerPayment.findMany({where:{orgId:org.id,contactId:crossContact.id}});
    assert.equal(crossPayments.reduce((n,p)=>n+Number(p.amount),0),successfulAmount);
    const reverseTarget=crossPayments[0];
    const reverse=()=>app.inject({method:'POST',url:'/api/v1/sale-app/debt/payments/'+reverseTarget.id+'/reverse',headers,payload:{}});
    const reversals=await Promise.all([reverse(),reverse()]);
    assert.equal(reversals.filter(r=>r.statusCode===200).length,1,'Exactly one reversal commits');
    assert(reversals.every(r=>[200,400,409].includes(r.statusCode)),reversals.map(r=>r.body).join(' '));
    const afterReverse=await prisma.order.findUniqueOrThrow({where:{id:crossOrder.id}});
    assert.equal(Number(afterReverse.paidAmount),successfulAmount-Number(reverseTarget.amount));
    assert.equal(Number(afterReverse.debtAmountValue),1000-successfulAmount+Number(reverseTarget.amount));
    const reverseAgain=await reverse();assert.equal(reverseAgain.statusCode,400,'Already reversed stays 400');
    const missingReverse=await app.inject({method:'POST',url:'/api/v1/sale-app/debt/payments/'+randomUUID()+'/reverse',headers,payload:{}});assert.equal(missingReverse.statusCode,404);
    console.log('PASS: fresh authorization, org scope, FIFO collection, exact retry, duplicate ref/hash block, expired draft, malformed bill, draft restore, attach preserving money/URLs, advance separate, stale snapshot, overpayment, concurrent retry, legacy/assistant cross-path concurrency, double reversal protection, strict dates/money');
}
finally {
    await prisma.receiptAssistantEvidence.deleteMany({ where: { orgId: org.id } });
    await prisma.receiptAssistantDraft.deleteMany({ where: { orgId: org.id } });
    await prisma.organization.delete({ where: { id: org.id } });
    await prisma.organization.delete({ where: { id: other.id } });
    await app.close();
    await prisma.$disconnect();
}
